"""
FAIRNESS_LLM_REVIEW node — LLM scans the rationale for identity bias language.

Purpose
-------
The structural fairness recheck (pure Python) already guarantees that
identity fields do not influence the *score*.  This node adds a second,
complementary layer: it asks an LLM to read the *rationale text* that will
be shown to the underwriter and check whether it contains any language that
references, implies, or could be influenced by protected characteristics
(name, nationality, gender, ethnicity, religion, age, address as a proxy, etc.).

Why both?
---------
- The Python recheck is structural — it proves identity did not affect the number.
- The LLM review is semantic — it checks that the *language* of the explanation
  is also free from bias, even if the number is correct.
  Example: a rationale could say "applicant lives in a high-risk postcode" —
  the score would be the same masked, but the language references location as
  a proxy for identity. The LLM review catches that.

Output
------
Sets state["fairness_llm_flag"] = True if the LLM finds any concern.
If flagged, the application is forced to REFER (same as structural mismatch).
The flag and the LLM's explanation are stored in FairnessCheck.llm_review_note.
"""

import logging

from app.models.scoring import ScoreBreakdown
from app.tools.github_models_client import call_model, get_primary_model

log = logging.getLogger(__name__)

_SYSTEM_PROMPT = """\
You are a fairness compliance reviewer for a credit decisioning system.

Your job is to read a credit application rationale and check whether it
contains any language that:
1. References the applicant's name, nationality, ethnicity, religion, gender,
   age, or any other protected characteristic.
2. Uses location (postcode, neighbourhood, city) as a proxy for identity or
   demographic group.
3. Makes assumptions about the applicant based on who they are rather than
   their objective financial metrics (DTI ratio, credit history, employment).
4. Contains any wording that could be perceived as discriminatory or biased.

The rationale should be based ONLY on:
- Debt-to-income ratio
- Credit history length and flags
- Employment stability (months in current role)
- Policy clause citations

RESPONSE FORMAT (you must respond with exactly this JSON, nothing else):
{
  "bias_detected": true | false,
  "confidence": "high" | "medium" | "low",
  "explanation": "<one sentence — what was found, or 'No bias language detected'>"
}

If you are uncertain, set bias_detected to true and confidence to low.
It is safer to flag for human review than to miss a bias signal.
"""


def run_fairness_llm_review(
    rationale: str,
    score_breakdown: ScoreBreakdown,
    application_id: str,
) -> tuple[bool, str]:
    """
    Ask the LLM to scan the rationale for identity bias language.

    Parameters
    ----------
    rationale         : The plain-English rationale generated by RECOMMEND node.
    score_breakdown   : Used to provide context about what the rationale should
                        reference (score factors only).
    application_id    : For logging.

    Returns
    -------
    (bias_detected, explanation)
        bias_detected — True if the LLM found potential bias language
        explanation   — LLM's one-sentence explanation of its finding
    """
    import json as _json

    user_content = (
        f"Application ID: {application_id}\n\n"
        f"Score factors (what the rationale should reference):\n"
        f"  DTI ratio: {score_breakdown.dti_ratio:.3f} ({score_breakdown.dti_ratio * 100:.1f}%)\n"
        f"  Credit history sub-score: {score_breakdown.credit_history_subscore:.3f}\n"
        f"  Income stability sub-score: {score_breakdown.income_stability_subscore:.3f}\n"
        f"  Composite score: {score_breakdown.composite_score:.3f} (band: {score_breakdown.band})\n\n"
        f"Rationale to review:\n<rationale>\n{rationale}\n</rationale>\n\n"
        "Respond with the JSON object only."
    )

    messages = [
        {"role": "system", "content": _SYSTEM_PROMPT},
        {"role": "user",   "content": user_content},
    ]

    log.info("app=%s running LLM fairness language review", application_id)

    try:
        raw = call_model(
            model=get_primary_model(),
            messages=messages,
            temperature=0.0,
            max_tokens=200,
        )
        # Strip markdown fences if present
        cleaned = raw.strip()
        if cleaned.startswith("```"):
            lines = cleaned.splitlines()
            cleaned = "\n".join(lines[1:-1] if lines[-1].strip() == "```" else lines[1:])

        data = _json.loads(cleaned)
        bias_detected = bool(data.get("bias_detected", False))
        explanation   = str(data.get("explanation", "LLM fairness review completed."))

        log.info(
            "app=%s fairness_llm_review bias_detected=%s confidence=%s",
            application_id, bias_detected, data.get("confidence", "?"),
        )
        return bias_detected, explanation

    except Exception as exc:  # noqa: BLE001
        # If the LLM call or parse fails, err on the side of caution:
        # do NOT flag as biased (avoid blocking all applications on LLM outage),
        # but log prominently.
        log.warning(
            "app=%s fairness_llm_review failed (%s) — skipping LLM language check",
            application_id, exc,
        )
        return False, f"LLM review unavailable: {exc}"
